// <auto-generated />
using HotelListing.api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.api.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    partial class HotelListingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelListing.api.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "South Africa",
                            ShortName = "SA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United Kingdom",
                            ShortName = "UK"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Netherlands",
                            ShortName = "NL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "New Zealand",
                            ShortName = "NZ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "United States",
                            ShortName = "US"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Thailand",
                            ShortName = "TB"
                        });
                });

            modelBuilder.Entity("HotelListing.api.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cape Town",
                            CountryId = 1,
                            Name = "Lagoon Beach Hotel & Spa ",
                            Rating = 3.7000000000000002
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hluhluwe iMfolozi Park, 3815, KwaNompondo",
                            CountryId = 1,
                            Name = "Rhino Ridge Safari Lodge",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Address = "Liverpool",
                            CountryId = 2,
                            Name = "INNSiDE by Meliá",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 4,
                            Address = "York",
                            CountryId = 2,
                            Name = "Sandburn Hall",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 5,
                            Address = "London",
                            CountryId = 2,
                            Name = "Ritz Hotel",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 6,
                            Address = "Amsterdam",
                            CountryId = 3,
                            Name = "Met Hotel Amsterdam",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 7,
                            Address = "Groningen",
                            CountryId = 3,
                            Name = "The Market Hotel",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 8,
                            Address = "Zandvoort",
                            CountryId = 3,
                            Name = "Hotel Bell",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 9,
                            Address = "Wellington",
                            CountryId = 4,
                            Name = "James Cook Hotel Grand Chancellor",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 10,
                            Address = "Christchurch",
                            CountryId = 4,
                            Name = "Sudima Hotel Christchurch Airport",
                            Rating = 3.7999999999999998
                        },
                        new
                        {
                            Id = 17,
                            Address = "Auckland",
                            CountryId = 4,
                            Name = "Novotel Auckland",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 11,
                            Address = "Key West",
                            CountryId = 5,
                            Name = "The Capitana",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 12,
                            Address = "Perimeter Center, Atlanta",
                            CountryId = 5,
                            Name = "Hyatt House",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 13,
                            Address = "Orlando",
                            CountryId = 5,
                            Name = "Fairfield by Marriott Inn & Suites",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 14,
                            Address = "Chiang Mai Old TOwn, Chiang Mai",
                            CountryId = 6,
                            Name = "El Barrio Lanna- SHA Extra Plus",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 15,
                            Address = "Sathorn, Bangkok",
                            CountryId = 6,
                            Name = "Eastin Grand Hotel",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 16,
                            Address = "Patong Beach, Phuket",
                            CountryId = 6,
                            Name = "The Royal Paradise Hotel & Spa",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("HotelListing.api.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.api.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.api.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
